# Version of the config file. DO NOT TOUCH IT!
config-version: b1.0
# (EN,TR) Do not forget to write it in all capital.
Language: EN
# Whether completed orders should be removed from orders menu or not.
Remove-Completed-Orders: true